# SITE CONFIGURATION
title: Christopher's Blog # your site title
author: Christopher Ton # You :P
description: > # Meta description of Homepage
  A collection of my thoughts and experiments with data!
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://chriztopherton.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Christopher Ton
  links:
    - https://www.linkedin.com/in/chriztopherton/
    - https://github.com/chriztopherton

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Some of my featured projects and project discussions!

hero_img: posts/sf_bike_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: chriztopherton@gmail.com # email for form submission

github_username:  chriztopherton # replace with your_github_username or comment to remove link from footer

disqus:
  shortname: chriztopherton # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
